version: '3.7'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VER: 20.10.0
    tty: true
    volumes:
      - .:/home/node/app
      # node_modulesをコンテナ内に保持
      - /home/node/app/node_modules
    ports:
      - "5173:5173"
